server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/emreilgar90/CloudConfigRepoYml.git"
          default-label: main
          skip-ssl-validation: true
          username: emreilgar90
          password: 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

