server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.25:5432/DbAuth
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

myapplication:
  auth:
    ip: 192.168.1.25
    port: 9090
  user:
    ip: 192.168.1.25
    port: 9093
    feignurl: http://192.168.1.25:9093/v1/dev/userprofile

buuygulama:
  birdeger: "birdeğer"